distancia = float(input('Digite uma distância em metros: '))
print('A medida de {:.1f} metros corresponde a:'.format(distancia))
print(f'{distancia/1000} Km')
print(f'{distancia/100} Hm')
print(f'{distancia/10} Dam')
print(f'{distancia*10:.0f} Dm')
print(f'{distancia*100:.0f} Cm')
print(f'{distancia*1000:.0f} Mm')
