first_name = str(input('Your first name: '))
last_name = str(input('Your last name: '))
cpf = float(input('Your CPF: '))
age = int(input('Your age: '))
height = float(input('Your height: '))
address = str(input('Your address: '))
email = str(input('Your email: '))
phone_number = int(input('Your phone number: '))
print('_______________________________________________')
print(f'| FULL NAME     | {first_name} {last_name}')
print(f'| CPF           | {cpf}')
print(f'| AGE           | {age}')
print(f'| HEIGHT        | {height}')
print(f'| ADDRESS       | {address}')
print(f'| EMAIL         | {email}')
print(f'| PHONE NUMBER  | {phone_number}')
print('_______________________________________________')
