print('->>->>->>->>->>->>->>->>->>->>->>->>->>->>->>->>->>')
print('')
sentense = str(input('Type a sentence: ').lower().strip())
print(f"The letter A appeared {sentense.count('a')} times in the sentense.")
print(f"The letter A first appeared in {sentense.find('a')+1}")
print(f"The letter A last appeared in {sentense.rfind('a')+1}")
print('')
print('<><><><><><><><><><><><><><><><><><><><><><><><><><>')
